auto:
  runTasks:
    quick: true
    full: false
  e2eTest:
    quick: false
    full: false
  consolidateSpecs:
    quick: true
    full: true
  cleanCode:
    quick: false
    full: true
  validation:
    quick: false
    full: false
  gitPush: true
interfaces:
  - cli
worktree:
  source-branch: v3.0.0
  copy-files: []
