// Package facttable provides types and functions for reading/writing
// the .forge/fact-table.json file. Fact Table stores structured facts
// about the system under test (signatures, output formats, error codes, etc.)
// used by test generation and run-to-learn pipelines.
package facttable

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"
)

const (
	forgeDir = ".forge"
	factFile = "fact-table.json"

	// SourceStatic identifies facts from code reconnaissance.
	SourceStatic = "static"
	// SourceRuntime identifies facts from run-to-learn.
	SourceRuntime = "runtime"
	// SourceManual identifies facts added by users.
	SourceManual = "manual"

	// ConfidenceConfirmed means the fact was verified at runtime.
	ConfidenceConfirmed = "confirmed"
	// ConfidenceInferred means the fact was statically inferred.
	ConfidenceInferred = "inferred"
	// ConfidenceAssumed means the fact was generated by LLM.
	ConfidenceAssumed = "assumed"

	// KindSignature records function/method signatures.
	KindSignature = "signature"
	// KindOutputFormat records output format facts.
	KindOutputFormat = "output_format"
	// KindErrorCode records error code facts.
	KindErrorCode = "error_code"
	// KindSideEffect records side effect facts.
	KindSideEffect = "side_effect"
	// KindPrecondition records precondition facts.
	KindPrecondition = "precondition"
	// KindCompilationError records compilation error facts.
	KindCompilationError = "compilation_error"
	// KindRuntimeCrash records runtime crash facts.
	KindRuntimeCrash = "runtime_crash"
)

// ValidSources lists all valid source values.
var ValidSources = []string{SourceStatic, SourceRuntime, SourceManual}

// ValidConfidences lists all valid confidence values.
var ValidConfidences = []string{ConfidenceConfirmed, ConfidenceInferred, ConfidenceAssumed}

// ValidKinds lists all valid kind values.
var ValidKinds = []string{
	KindSignature, KindOutputFormat, KindErrorCode,
	KindSideEffect, KindPrecondition,
	KindCompilationError, KindRuntimeCrash,
}

// FactEntry represents a single fact in the Fact Table.
type FactEntry struct {
	FactID     string          `json:"fact_id"`
	Source     string          `json:"source"`
	Subject    string          `json:"subject"`
	Kind       string          `json:"kind"`
	Value      json.RawMessage `json:"value"`
	Confidence string          `json:"confidence"`
	UpdatedAt  string          `json:"updated_at"`
}

// FactTable represents the entire fact table stored as an array of FactEntry.
type FactTable []*FactEntry

// FactFilePath returns the path to .forge/fact-table.json for a given project root.
func FactFilePath(projectRoot string) string {
	return filepath.Join(projectRoot, forgeDir, factFile)
}

// Load reads the fact table from .forge/fact-table.json.
// Returns an empty table if the file doesn't exist.
// Returns an error with recovery hints if the file contains invalid JSON.
func Load(projectRoot string) (FactTable, error) {
	path := FactFilePath(projectRoot)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return FactTable{}, nil
		}
		return nil, fmt.Errorf("read fact table: %w", err)
	}

	// Empty file is treated as empty table
	if len(data) == 0 {
		return FactTable{}, nil
	}

	var table FactTable
	if err := json.Unmarshal(data, &table); err != nil {
		return nil, &CorruptError{
			Path:    path,
			Details: err.Error(),
		}
	}

	return table, nil
}

// Save writes the fact table to .forge/fact-table.json.
// Creates the .forge directory if it doesn't exist.
func Save(projectRoot string, table FactTable) error {
	path := FactFilePath(projectRoot)

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create .forge dir: %w", err)
	}

	data, err := json.MarshalIndent(table, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal fact table: %w", err)
	}

	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write fact table: %w", err)
	}

	return nil
}

// CorruptError represents a corrupted fact-table.json file.
type CorruptError struct {
	Path    string
	Details string
}

func (e *CorruptError) Error() string {
	return fmt.Sprintf("corrupted fact table: %s: %s", e.Path, e.Details)
}

// Hint returns a recovery hint for the user.
func (e *CorruptError) Hint() string {
	return fmt.Sprintf("Fix JSON syntax in %s or delete it to start fresh", e.Path)
}

// Filter filters the fact table by the given source and confidence.
// Empty string means "no filter" (match all).
func (t FactTable) Filter(source, confidence string) FactTable {
	var result FactTable
	for _, entry := range t {
		if source != "" && entry.Source != source {
			continue
		}
		if confidence != "" && entry.Confidence != confidence {
			continue
		}
		result = append(result, entry)
	}
	return result
}

// GetByID finds a fact entry by its fact_id. Returns nil if not found.
func (t FactTable) GetByID(factID string) *FactEntry {
	for _, entry := range t {
		if entry.FactID == factID {
			return entry
		}
	}
	return nil
}

// SummaryStats holds statistics about the fact table.
type SummaryStats struct {
	BySource     map[string]int `json:"by_source"`
	ByConfidence map[string]int `json:"by_confidence"`
	ByKind       map[string]int `json:"by_kind"`
	Total        int            `json:"total"`
}

// Summary computes statistics grouped by source, confidence, and kind.
func (t FactTable) Summary() SummaryStats {
	stats := SummaryStats{
		BySource:     make(map[string]int),
		ByConfidence: make(map[string]int),
		ByKind:       make(map[string]int),
		Total:        len(t),
	}

	for _, entry := range t {
		stats.BySource[entry.Source]++
		stats.ByConfidence[entry.Confidence]++
		stats.ByKind[entry.Kind]++
	}

	return stats
}

// EffectiveEntries returns the effective fact entries after applying
// runtime-to-static replacement semantics:
//   - runtime confirmed replaces static of same subject+kind
//   - runtime non-confirmed keeps static as fallback
func (t FactTable) EffectiveEntries() FactTable {
	type key struct{ subject, kind string }

	type entryGroup struct {
		static  []*FactEntry
		runtime *FactEntry
	}
	groups := make(map[key]*entryGroup)

	for _, e := range t {
		k := key{e.Subject, e.Kind}
		g, ok := groups[k]
		if !ok {
			g = &entryGroup{}
			groups[k] = g
		}
		switch e.Source {
		case SourceStatic, SourceManual:
			g.static = append(g.static, e)
		case SourceRuntime:
			g.runtime = e
		}
	}

	var result FactTable
	for _, g := range groups {
		if g.runtime != nil {
			result = append(result, g.runtime)
			// If runtime is not confirmed, keep static as fallback
			if g.runtime.Confidence != ConfidenceConfirmed && len(g.static) > 0 {
				result = append(result, g.static...)
			}
		} else {
			result = append(result, g.static...)
		}
	}

	return result
}

// GenerateNonce creates a short nonce for fact_id uniqueness.
func GenerateNonce() string {
	return fmt.Sprintf("%d", time.Now().UnixMilli()%100000)
}

// SortedEntries returns entries sorted by fact_id for stable output.
func (t FactTable) SortedEntries() FactTable {
	sorted := make(FactTable, len(t))
	copy(sorted, t)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].FactID < sorted[j].FactID
	})
	return sorted
}

// Validate checks if a FactEntry has valid field values.
func (e *FactEntry) Validate() error {
	if e.FactID == "" {
		return fmt.Errorf("fact_id is required")
	}
	if !isValidValue(e.Source, ValidSources) {
		return fmt.Errorf("invalid source: %q (valid: %v)", e.Source, ValidSources)
	}
	if e.Subject == "" {
		return fmt.Errorf("subject is required")
	}
	if !isValidValue(e.Kind, ValidKinds) {
		return fmt.Errorf("invalid kind: %q (valid: %v)", e.Kind, ValidKinds)
	}
	if !isValidValue(e.Confidence, ValidConfidences) {
		return fmt.Errorf("invalid confidence: %q (valid: %v)", e.Confidence, ValidConfidences)
	}
	if len(e.Value) == 0 {
		return fmt.Errorf("value is required")
	}
	if e.UpdatedAt == "" {
		return fmt.Errorf("updated_at is required")
	}
	return nil
}

func isValidValue(val string, valid []string) bool {
	for _, v := range valid {
		if v == val {
			return true
		}
	}
	return false
}
